### ISSUE TITLE
video length 

### ISSUE THREAD

**Issue by zcdliuwei** [magic-research/magic-edit#1]
Thanks for your great work!
May I ask how long video length this method can support？

**Comment by liewjunhao** [comment]
Thank you. The videos in our project page are 2 seconds long each. Additionally, we have also verified that our method can support longer video length (3-4 seconds).

**Comment by zcdliuwei** [comment]
> Thank you. The videos in our project page are 2 seconds long each. Additionally, we have also verified that our method can support longer video length (3-4 seconds).

Thanks  again for your reply and the interesting project !
