### ISSUE TITLE
请问，何时发布代码？

### ISSUE THREAD

**Issue by juntaosun** [magic-research/magic-edit#6]
有具体的发布时间吗，注意到，大家对此都充满了期待。
Is there a specific release time? I noticed that everyone is looking forward to it.
具体的な発売時期はありますか?みんな楽しみにしています。
구체적인 출시 시간이 있습니까? 모두가 기대하고 있다는 것을 알았습니다.
มีเวลาวางจำหน่ายที่แน่นอนหรือไม่ โปรดทราบว่าทุกคนตั้งตารอคอยสิ่งนี้
Есть конкретное время выпуска? Я заметила, что все с нетерпением ждут этого.
Có thời gian phát hành cụ thể không, lưu ý rằng mọi người đều đầy kỳ vọng vào điều này.

**Comment by Bailey-24** [comment]
笑不活了，七种语言来问

**Comment by Samge0** [comment]
同问。 (Chinese)
Ditto. (English)
私も同じです。 (Japanese)
저도 궁금합니다. (Korean)
ผมก็อยากรู้เหมือนกัน (Thai)
Тоже самое. (Russian)
Tôi cũng vậy. (Vietnamese)

**Comment by 18445864529** [comment]
It has been 五个月了，perhapsもう不会再发布了だと思います。

**Comment by hg3386628** [comment]
mark 一下 ,发了代码T我一下

**Comment by juntaosun** [comment]
感觉是被放鸽子了，PPT开源，已取消关注~
